name: inf

channels:
  - intel
  - mosek
  - conda-forge

dependencies:
  - python=3
  - numpy
  - scipy
  - numba
  - mosek
  - numpydoc
  - pip:
      - intel-openmp
      - mkl
      - cvxopt
      - igraph
